name: Test

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login Docker Hub
        run: make dockerhub-login
        env: 
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Pull built Docker image 
        run: make docker-pull
      - name: Build Docker image
        run: make docker-run
      - name: Push Docker image
        run: make docker-push
  test:
    name: Run tests
    runs-on: ubuntu-latest
    needs: build      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login Docker Hub
        run: make dockerhub-login
        env: 
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Retrieve and build image
        run: make docker-pull && make docker-build
      - name: Run tests
        run: make test
        env: 
          WATER_BOT_TOKEN: ${{ secrets.WATER_BOT_TOKEN }}
